config/routes.rb
Rails.application.routes.draw do
  resources :gossips do 
    resources :comments
    resources :users
    resources :cities
  end
  
  
  root 'index#home'
  get '/team', to: 'index#team'
  get '/contact', to: 'index#contact'
  
  # get '/welcome/:name', to: 'index#welcome'
  # get 'cities/show'
  
end

app/models/application_record copy.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tags, through: :hashtags
  has_many :comments

  validates :title,
    presence: true,
    length: {minimum: 3, maximum: 14}

  validates :content,
    presence: true
    
end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
  belongs_to :user
  belongs_to :private_message
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

  belongs_to  :user
  has_many :users, through: :mailboxes
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips, through: :hashtags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :private_messages, through: :mailboxes
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger 
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

 
  def index
    @gossips = Gossip.all
  end

  
  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: User.all.sample.id)
    if @gossip.save
     
      redirect_to root_path 
    else
      
      render new_gossip_path 
    end
  end
  
  
  def new
    @gossip = Gossip.new
  end

  
  def edit
    @gossip = Gossip.all.find_by(id:params[:id])
  end

  
  def show
    @gossip = Gossip.all.find_by(id: params[:id])
   
    
    
  end

  
  def update
    
  end

  
  def destroy
    @gossip = Gossip.find(params[:id])
    if @gossip.destroy
     
      redirect_to root_path, success: "Gossip suprimé"
    else
      
      redirect_to root_path, danger: "Echec"
    end
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
    @gossips = Gossip.all
  end

  def team
  end

  def contact
  end

  def welcome
    @gossips = Gossip.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  end

  def create

  end
  
  def new
    
  end

  def edit
    
  end

 
  def show
    @user = Gossip.all.find_by(id: params[:id])
    puts @city_id = @user.user.city_id
    @city_name = City.find_by(id: @city_id).name
  end

  def update
    
  end

  def destroy
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
  <div class="container container_create">
<div class="card contact_card card_create" 
<%= form_tag gossips_path, method: "post" do %>
  <%= label_tag 'TITRE' %>
  <%= text_field_tag 'title', @gossip.title %> 
  <br /> <br />

  <%= label_tag 'Le gossip'  %>
  <%= text_area_tag 'content', @gossip.content %> 
  
  

 

<% end %>

</div>
</div>

app/views/gossips/new.html.erb
<div class="container container_create">
<div class="card contact_card card_create" 
<%= form_tag gossips_path, method: "post" do %>
  <%= label_tag 'Ton titre' %>
  <%= text_field_tag 'title', @gossip.title %> 
  <br /> <br />

  <%= label_tag 'Ton contenu'  %>
  <%= text_area_tag 'content', @gossip.content %> 
  <br /> 
  <p >Et tu </p>
  <br />

  <%= submit_tag "VALIDE" %>

<% end %>

</div>
</div>

app/views/index/contact.html.erb
<div class="container contact">

<div class="row">

  

  <div class="card contact_card" 
  style="background-color: rgb(235, 245, 245);"> 
    <form id="contact-form" method="post" action="" role="form">

    <div class="messages"></div>

    <div class="controls">

      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="form_name">Firstname *</label>
            <input id="form_name" type="text" name="name" class="form-control" placeholder="Please enter your firstname *" required="required" data-error="Firstname is required.">
            <div class="help-block with-errors"></div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="form_lastname">Lastname *</label>
            <input id="form_lastname" type="text" name="surname" class="form-control" placeholder="Please enter your lastname *" required="required" data-error="Lastname is required.">
            <div class="help-block with-errors"></div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="form_email">Email *</label>
            <input id="form_email" type="email" name="email" class="form-control" placeholder="Please enter your email *" required="required" data-error="Valid email is required.">
            <div class="help-block with-errors"></div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="form_phone">Phone</label>
            <input id="form_phone" type="tel" name="phone" class="form-control" placeholder="Please enter your phone">
            <div class="help-block with-errors"></div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="form_message">Message </label>
            <textarea id="form_message" name="message" class="form-control" placeholder="Message for me *" rows="4" required data-error="Please,leave us a message."></textarea>
            <div class="help-block with-errors"></div>
          </div>
        </div>
        <div class="col-md-12">
          <input type="submit" class="btn btn-success btn-send" value="Send message">
        </div>
      </div>
     
    </div>

    </form>

  </div>

</div>

</div>

app/views/index/home.html.erb
<div class="container">


<div class="creer_gossip">
<h2 class="titre_gossip">TU PEUX CREER TON GOSSIP</h2>
    <%= link_to "ICI", new_gossip_path, class: "btn btn-primary btn_fait_ton_goosip " %>        
</div>

<p class="para_juste">OU JUSTE REGARDER LA</p>

<h1 class="titre_gossips_list">GOSSIPS LIST</h1>

<div class="card-columns z_index">
<% @gossips.each_with_index do |gossip, index| %>
  <div>


    <div class="card " 
    style="background-color: rgb(235, 245, 245);">

    <div class="card-body">
    
    <h3> NAME: </h4> <p class="taille_police"><%= gossip.user.last_name%></p>
    <h3> TITLE:</h4> <p class="taille_police"><%= gossip.title %>       </p>
    <h3> AJOUT:</h4> <p class="taille_police"><%= gossip.created_at %>  </p>
        
    
    
    <%= link_to "READ", edit_gossip_path(gossip.id), class: "btn btn-primary btn_read"%>    
    <%= link_to "DELETE", gossip_path(gossip.id), method: :delete, data: {confirm: "Voulez- vous vraiment le suprimer"}, class: "btn btn_color" %>     
    </div>
    </div>

  <% end %>
</div>
</div>

app/views/index/team.html.erb
<div class="container container_team">

  <div class= divteam>
    <h1>Voici notre equipe </h1>
    <br>
    <p>Florence est le seul membre de cette equipe 🤪</p>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light barre">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand " href="#">GOSSIP <br>PROJECT</a>
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
  
          <li class="nav-item">
          <a > <%= link_to "HOME", root_path, class: 'css_lien_navbarre' %></a>
          </li> 
          <li class="nav-item">
              <a><%= link_to "TEAM", team_path , class: 'css_lien_navbarre'%></a>
          </li>
          <li class="nav-item active">
              <a><%= link_to "CONTACT", contact_path, class: 'css_lien_navbarre'%></a>
          </li>
        
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
    </header>
  <%= yield%>
    
  </body>
</html>